name: MoneySystem
version: '${version}'
main: de.bloon.moneysystem.MoneySystem
api-version: '1.16'

commands:
  money:
    description: shows the balance of a player
    aliases:
      - "geld"
  eco:
    description: manage all player balances
    aliases:
      - "eco"
  setsql:
    description: sets if the plugin should use a mysql database
    aliases:
      - "setmysql"
      - "setusedatabase"
  pay:
    description: pay a player a specified amount of money
    aliases:
      - "pay"
      - "bezahlen"
  setname:
    description: changes the name of the secondary currency
    aliases:
      - "setzename"
  pluginrestart:
    description: restarts the plugin
    aliases:
      - "restartplugin"
